### ISSUE TITLE
Adding Responsivity

### ISSUE THREAD

**Issue by abdallah-alshawaf** [CA-G12/Quiz-App-Team-14#30]
We need a structure for adding responsivity. Should we agree on the widths or just each one design his own page to become responsive?

**Comment by ysalem-dev-89** [comment]
Yes we should agree on breakpoints, how about these
768px -> for small devices
992px -> for medium devices
1200px -> for large devices
1800px -> for big desktops

**Comment by abdallah-alshawaf** [comment]
I think that smaller devices deserve more breakpoints. 
I usually use: 
320px
480px
600px
768px
900px
1024px 

If we handled the media queries in a good way in 600px, we might not need the other smaller ones.

**Comment by ysalem-dev-89** [comment]
OK, that seems nice, let's do it, I will assign this issue to Sara.

**Comment by abdallah-alshawaf** [comment]
Alright, that sounds good. What about file structure? Should we add the media queries to the end of each css file?

**Comment by ysalem-dev-89** [comment]
That's up to you, both ways are right, for myself I would prefer to add media query after each css selector that I want to change.

**Comment by abdallah-alshawaf** [comment]
Okay, I'll do that to reduce files.
