### ISSUE TITLE
some minor changes to the code

### ISSUE THREAD

**Issue by abdallah-alshawaf** [CA-G12/Quiz-App-Team-14#31]
1. I think the time would be better if it is 20 seconds. 
2. There's an issue when the time ends. When it ends, while I'm selecting an answer, it doesn't count that answer at all. I need to press Next for the answer to count. What if the app sees if you selected an answer at the end of the timer, if yes, it counts it, else, it doesn't count.

**Comment by abdallah-alshawaf** [comment]
I have read your code and it's absolutely brilliant. I would love for you to teach me about a few things one day. 

I think the solution would be to add 

if (checkAnswer(currentIndex)) {
    correctAnswers = correctAnswers + 1;
  } 

at the end of the timer, but I'll leave this change and others to you.

**Comment by ysalem-dev-89** [comment]
Thanks Abdallah, this is nice thing to hear, sure I would love that we exchange experiences and benefit from each other.

About time duration I have changed it to 20 sec and anyway we can change it now in the const variable QUESTION_TIME in quiz.js file

For the idea of counting answer even if the user didn't press next, it is great idea, and the solution is like you mentioned,
so I have just applied it in the new version.
